[project]
name = "notebooks"
version = "0.1.0"
requires-python = "==3.12.*"

dependencies = [
    # Base packages
    "wheel~=0.46.2",
    "setuptools~=80.9.0",

    # Datascience packages
    "boto3~=1.40.27",
    "kafka-python-ng~=2.2.3",
    "matplotlib~=3.10.6",
    "numpy~=2.3.3",
    "pandas~=2.3.2",
    "plotly~=6.3.0",
    "scikit-learn~=1.7.2",
    "scipy~=1.16.1",
    "skl2onnx~=1.19.1",
    "ipykernel~=6.30.1",
    "kubeflow-training==1.9.3",
    "feast~=0.54.1",

    # Some extra useful packages
    "opencensus~=0.11.4",
    "smart-open~=7.3.1",
    "virtualenv~=20.34.0",
    "py-spy~=0.4.1",
    "prometheus-client~=0.22.1",
]

[tool.uv]
environments = [
    "sys_platform == 'linux' and implementation_name == 'cpython'",
]
override-dependencies = [
    # RHAIENG-2458: CVE-2025-66418 urllib3 decompression vulnerability
    # Upstream: https://github.com/kubernetes-client/python/issues/2458
    "urllib3>=2.6.0",
]